name: Test and Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stable'

env:
  AZURE_AD_APP_ID: 451f36c7-ae84-4cdc-a13d-68c75f88fc8c
  AZURE_WEBAPP_NAME: connect-admin-enosix
  RESOURCE_GROUP: mgmt-dashboard

permissions:
  contents: write
  packages: read

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            d494f42b-8a60-431a-aef9-b18501149f57 > AZURE_AD_CLIENT_ID
            80ba47f3-5ce7-493a-8c79-b1850114b58b > AZURE_AD_CLIENT_SECRET
            370453a3-d0da-46f4-a456-b1850114f67e > AZURE_AD_TENANT_ID
      - uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          allow-no-subscriptions: true
          creds: |
            {
              "clientId": "${{ env.AZURE_AD_CLIENT_ID }}",
              "clientSecret": "${{ env.AZURE_AD_CLIENT_SECRET }}",
              "tenantId": "${{ env.AZURE_AD_TENANT_ID }}",
              "resourceManagerEndpointUrl": "https://management.azure.com/"
            }
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            } catch (err) {
              console.log(err)
            
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            }
